### ISSUE TITLE
Kubernetes function support? 

### ISSUE THREAD

**Issue by tkg61** [EtiennePerot/open-webui-code-execution#1]
Trying to run this in the helm deployment of Openwebui but i am just getting an error with no debug logs from openwebui on the console, just this in the browser. 

ERROR: Sandbox runtime failed: Sandbox failed to start: Command '['/tmp/gvisor/runsc', '--rootless=true', '--directfs=false', '--network=host', '--ignore-cgroups=true', '--root=/tmp/sandbox_5fy9e757/runtime', '--debug=false', '--debug-log=/tmp/sandbox_5fy9e757/logs/', 'run', '--bundle=/tmp/sandbox_5fy9e757/bundle', 'sandbox']' returned non-zero exit status 128.; stderr: Error executing inside namespace: re-executing self: fork/exec /proc/self/exe: operation not permitted; logs: defaultdict(<class 'list'>, {'runsc.log.20240903-202454.703685.run.txt': ['W0903 20:24:54.704233     114 util.go:64] FATAL ERROR: Error executing inside namespace: re-executing self: fork/exec /proc/self/exe: operation not permitted', 'W0903 20:24:54.704341     114 main.go:231] Failure to execute command, err: 1']})

**Comment by EtiennePerot** [comment]
I believe the steps to make this work on Kubernetes are now fully documented on [the setup docs](https://github.com/EtiennePerot/open-webui-code-execution/blob/master/docs/setup.md). Please reopen if they don't work for you.
