### ISSUE TITLE
"Unhandled exception: name '__file__' is not defined"

### ISSUE THREAD

**Issue by EtiennePerot** [EtiennePerot/open-webui-code-execution#11]
Open WebUI commit https://github.com/open-webui/open-webui/commit/cf86ba778605bf0e7494817e83dbf940c0086277 breaks this tool due to tools and functions no longer being written to files on disk. The tool and function re-execute themselves as subprocesses in order to function, by using Python's special `__file__` global variable which is normally defined for modules when they are imported.

This manifests in Open WebUI as an error saying: `Unhandled exception: name '__file__' is not defined`.

**Comment by uzza1hossain** [comment]
Facing same issue.

**Comment by EtiennePerot** [comment]
Sorry about that. The fix needs to happen in Open WebUI first, not this tool. I have a fix for Open WebUI at https://github.com/EtiennePerot/open-webui/commit/6477bf37fec3f736aa659c3a9e1de1d09cad5365 which I will send as a PR tomorrow and hope they accept it.

In the meantime, as a workaround, you can use an older version of Open WebUI; basically any version older than https://github.com/open-webui/open-webui/commit/cf86ba778605bf0e7494817e83dbf940c0086277. For example, if you are using the Open WebUI container image, I've verified that `ghcr.io/open-webui/open-webui:git-27109d2` is old enough to not have this problem.

**Comment by EtiennePerot** [comment]
A PR to fix this was sent to Open WebUI here: https://github.com/open-webui/open-webui/pull/5511

**Comment by EtiennePerot** [comment]
This was merged and available in Open WebUI v0.3.22. However the tool has not been updated to work with it yet. Will post here when the fix is released.

**Comment by EtiennePerot** [comment]
This issue is fixed as of release 0.6.0.
