### ISSUE TITLE
use an external library

### ISSUE THREAD

**Issue by codeMonkey-shin** [EtiennePerot/open-webui-code-execution#17]
I use minio that provide the file to the corresponding code executor

I'm also going to try a function where the code executor uploads the completed file back to minio.

How do I enable the code executor to use an external library?

**Comment by EtiennePerot** [comment]
This is not supported yet. See issue #15.

**Comment by EtiennePerot** [comment]
That being said, as a workaround, you can currently pre-install minio in your Docker image and then it will be available to Python code execution, like so:

```
FROM ghcr.io/open-webui/open-webui:main
RUN pip install minio
```

Then you can use this image instead of the Open WebUI one, and code execution should be able to use minio.

**Comment by codeMonkey-shin** [comment]
Can gvisor use the libraries of the openwebui container?

**Comment by EtiennePerot** [comment]
Yes, so preinstalling libraries in the openwebui container will let them become usable for code execution.
