### ISSUE TITLE
Download large generated files

### ISSUE THREAD

**Issue by lu4p** [EtiennePerot/open-webui-code-execution#7]
I often use ChatGPT to generate or edit files. I think there is currently no way to output large files.

### Example using ChatGPT
Prompt:

Generate a textfile with 1000 uuids

Answer:

I have generated a text file containing 1000 UUIDs. You can download it using the link below:

[Download UUIDs file](#) ​

Executed code:
```
import uuid

# Generate a list of 1000 UUIDs
uuid_list = [str(uuid.uuid4()) for _ in range(1000)]

# Save to a text file
file_path = '/mnt/data/uuids.txt'
with open(file_path, 'w') as f:
    for uid in uuid_list:
        f.write(uid + '\n')

file_path
```
​

**Comment by EtiennePerot** [comment]
In case anyone stumbles upon this issue later :This is a duplicate of issue #4, so follow that one instead.
